### PR TITLE
Fix merge pipeline

### LINKED ISSUE #6: Create Github action for documentation generation and deployment

### PR DESCRIPTION
**Pull request by RobinWijnant**
See reopened issue #6 
- Removing the execution away from the container is a possible fix for the failing git commit
- `tsc --build` or `tsc -b` is used to only update the changed files. The dist is always deleted so adding this flag is redundant. The verbose flag is also not needed imo.

Closes #6

### CODE REVIEW

**Comment by RobinWijnant** [comment]
The failing git commit is caused by the EndBug/add-and-commit action. I have opened an issue on the repo. See https://github.com/EndBug/add-and-commit/issues/27

**Comment by bramvanhoutte** [comment]
Is there really not another way of deploying the docs? Because now the PR is always going to be cluttered with the built documentation files

**Comment by RobinWijnant** [comment]
What do you mean with cluttered? Is the automatic commit bothering you? What do you propose?

**Comment by bramvanhoutte** [comment]
Right now there are 43 changes. But these are generated build files, meaning they will change every time a new build is done. This means that every pull request will have 40+ changes, which is really annoying to filter through when reviewing.

**Comment by RobinWijnant** [comment]
Normally the commit with the generated doc folder only occurs after the merge in master. I wanted to test if it worked without waiting for the merge. This leaded to the docs already being commited in this branch. I think this was confusing.

I removed the generated docs from this branch. I am also thinking of using a seperate branch to publish the docs folder. It will also help keeping a clean commit history on master. What do you think?

**Pull request merged**
